In [1]:
import numpy as np
import tensorflow as tf

ImportError: Traceback (most recent call last):
  File "/home/yangfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/yangfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/yangfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/yangfei/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yangfei/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/yangfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so)


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

In [3]:
X_ = np.array([[-1., -2.], [-1, -2]])
W_ = np.array([[2., -3], [2., -3]])
b_ = np.array([-3., -5])

In [21]:
x =np.dot(X_, W_)

In [22]:
b = np.repeat(b_[:,None], 2, axis=1)


In [23]:
x + b.T

array([[-9.,  4.],
       [-9.,  4.]])

In [25]:
x + b_

array([[-9.,  4.],
       [-9.,  4.]])

In [27]:
x

array([[-6.,  9.],
       [-6.,  9.]])

In [28]:
w1  = np.array([[1, 2], [3, 4]])
w2  = np.array([[5, 6], [7, 8]])

# flatten
w1_flat = np.reshape(w1, -1)
w2_flat = np.reshape(w2, -1)

In [29]:
w1_flat

array([1, 2, 3, 4])

In [30]:
w2_flat

array([5, 6, 7, 8])

In [33]:
def _sigmoid_2_derivative( x):
    return x * (1 - x)

In [34]:
y = np.array([2, 3])
_sigmoid_2_derivative(y)

array([-2, -6])

In [35]:
y2 = np.array([[2], [3]])
_sigmoid_2_derivative(y2)

array([[-2],
       [-6]])

In [36]:
np.dot(y, y)

13

In [40]:
y[:,None]*y[:, None]


array([[4],
       [9]])

In [41]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'